---
title: ""
---

# About {#sec-about}

I am a Lab Fellow in the American Politics Research Lab and a PhD Candidate in the Department of Political Science at the University of Colorado Boulder. I am a computational social scientist that researches political psychology, political communication, race and gender, and the utility of applied machine learning and Bayesian statistics for causal inference. Overall, my research seeks to address the question: "how does politics affect the brain?" My dissertation, and book project, examines the cognitive processes that occur to explain how color acts as a form of political information. My other projects in progress examine tools to solve missing data problems, how gender and racial attitudes may be connected, and how a common identity among whites may inform their political attitudes. My academic work is featured in *Political Behavior*, *Political Research Quarterly*, *Social Science Quarterly*, and *American Politics Research*. My public-facing scholarship is featured in *The Washington Post*'s Monkey Cage Blog.

# Contact

<a class="button1" href ="mailto:damon.charles.roberts@gmail.com">
    <i class="fa-solid fa-envelope"></i> Email
</a>
<a class="button1" href="https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MzRlMG1yZnJtNWhkdjFiam1lOHVuMGgyYTNfMjAyMzAxMTlUMTkwMDAwWiBjX2NjMTYwNWZiMjc0YTU1NjM2YTNiYzY4N2Q2M2ZhMjQ0NzhiZGQwZGZhMGFkMjM1MDFmNjkyM2IxZDQxZDc0MGZAZw&tmsrc=c_cc1605fb274a55636a3bc687d63fa24478bdd0dfa0ad23501f6923b1d41d740f%40group.calendar.google.com&scp=ALL">
    <i class="fa-solid fa-clock"></i> Office Hours
</a>
<a class="button1" href="https://github.com/damoncharlesroberts">
    <i class="fa-brands fa-github"></i> Github
</a>
<a class="button1" href="https://www.linkedin.com/in/damon-roberts-00a08a197">
    <i class="fa-brands fa-linkedin"></i> LinkedIn
</a>
<a class="button1" href="https://mastodon.social/@damoncroberts">
    <i class="fa-brands fa-mastodon"></i> Mastodon
</a>