project:
  type: book
  output-dir: (root)

book:
  title: "PSCI 2075 Recitation Handout"
  author: "Damon C. Roberts"
  date: today
  chapters:
    - index.qmd
    - handout.qmd
    - 01_setup.qmd
    - 02_anatomy.qmd
    - 03_run_code.qmd
    - 04_quarto.qmd
    - 05_r_syntax_basics.qmd
    - 06_loading_data.qmd
    - references.qmd
toc-depth: 2
bibliography: references.bib

format:
  html:
    theme:
      - journal
      - ../assets/custom.scss
  pdf:
    documentclass: scrreprt
execute:
  freeze: auto
