# Recitation Handout {.unnumbered #sec-handout}

## Recitation Information

### Section 011
|                            |                                                                           |         |
|---------------------------:|--------------------------------------------------------------------------:|:-------:|
| Instructor: Damon C. Roberts | Email: [damon.roberts-1@colorado.edu](mailto:damon.roberts-1@colorado.edu) | 
| Meeting time: Friday: 10:10-11:00 AM |   Meeting Location: Koelbel 140 | [Add to Google Calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=Nm5oaGZscGlxbWRwb3BoMjNvaGxjcXFzaWVfMjAyMzAxMjBUMTcxMDAwWiBjX2NjMTYwNWZiMjc0YTU1NjM2YTNiYzY4N2Q2M2ZhMjQ0NzhiZGQwZGZhMGFkMjM1MDFmNjkyM2IxZDQxZDc0MGZAZw&tmsrc=c_cc1605fb274a55636a3bc687d63fa24478bdd0dfa0ad23501f6923b1d41d740f%40group.calendar.google.com&scp=ALL)
| Office hours: Mondays and Thursdays: 12-1 PM| Office: Ketchum 382 | [Add to Google Calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MzRlMG1yZnJtNWhkdjFiam1lOHVuMGgyYTNfMjAyMzAxMTlUMTkwMDAwWiBjX2NjMTYwNWZiMjc0YTU1NjM2YTNiYzY4N2Q2M2ZhMjQ0NzhiZGQwZGZhMGFkMjM1MDFmNjkyM2IxZDQxZDc0MGZAZw&tmsrc=c_cc1605fb274a55636a3bc687d63fa24478bdd0dfa0ad23501f6923b1d41d740f%40group.calendar.google.com&scp=ALL) |

### Section 018
|                            |                                                                           |         |
|---------------------------:|--------------------------------------------------------------------------:|:-------:|
| Instructor: Damon C. Roberts | Email: [damon.roberts-1@colorado.edu](mailto:damon.roberts-1@colorado.edu) | 
| Meeting time: Thursday: 10:10-11:00 AM |   Meeting Location: MCOL E155 | [Add to Google Calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=NHM5dnBzM2YzOHFndWM4amRsZG11ZDI0a2tfMjAyMzAxMTlUMTcxMDAwWiBjX2NjMTYwNWZiMjc0YTU1NjM2YTNiYzY4N2Q2M2ZhMjQ0NzhiZGQwZGZhMGFkMjM1MDFmNjkyM2IxZDQxZDc0MGZAZw&tmsrc=c_cc1605fb274a55636a3bc687d63fa24478bdd0dfa0ad23501f6923b1d41d740f%40group.calendar.google.com&scp=ALL)
| Office hours: Mondays and Thursdays: 12-1 PM| Office: Ketchum 382 | [Add to Google Calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MzRlMG1yZnJtNWhkdjFiam1lOHVuMGgyYTNfMjAyMzAxMTlUMTkwMDAwWiBjX2NjMTYwNWZiMjc0YTU1NjM2YTNiYzY4N2Q2M2ZhMjQ0NzhiZGQwZGZhMGFkMjM1MDFmNjkyM2IxZDQxZDc0MGZAZw&tmsrc=c_cc1605fb274a55636a3bc687d63fa24478bdd0dfa0ad23501f6923b1d41d740f%40group.calendar.google.com&scp=ALL) |

## Purpose of a recitation

The purpose of my part in delivering the course for you, as all college courses should be viewed, is not to "lose points" or to earn a grade. Rather, I see our journey this semester as a collaborative effort for you to build knowledge to make you a more effective democratic citizen and for me to work with the instructor of record to give you a very small introduction to a potential career path. We provide you with information we think is relevant for this goal and your job is to learn it.

Recitations meet separately from lecture but are still required. The purpose of a recitation, especially for large classes, is to help you, the student, to have a meeting time separate from lecture that reviews the lecture material and to provide a more in depth conversations. Recitations are a supplement to what you learn in lecture. In the recitation, broadly speaking, we will review and discuss the assigned readings for the class and will clarify any points of confusion from the material covered in the lecture. For this recitation, we will also take a deeper dive into the R code that allows researchers to perform many of these statistical computations we discuss in lecture. As a student, your goal for the recitation is to come prepared with questions and if you have none to do the work to understand the material. My goal as the instructor for this recitation is to guide your learning so that you get more in-depth understanding of the material for the class. For many, this is a required class that you are taking to complete your degree and are not interested in the material. My other goal is to persuade you of the importance of understanding the statistical concepts so that you may be competent consumers of political data and research; as well as to demonstrate the importance of argumentation with data analysis.

The format of the recitations and the material for the course is determined by the faculty teaching the class. I, however, will do what I can to be flexible to the needs of the students for my recitations to maximize your learning.

## Contacting me

You should feel free to contact me throughout the semester. I encourage you to come to office hours (what I refer to as student hours) so that I can help answer any questions you have about the course policies, the material covered in the class, any concerns you have, questions about navigating University, offering additional materials if there is a topic you are really interested in, etcetera. You are also welcomed to email me. I am usually responsive to email Monday-Friday from 9 AM – 5 PM (I may take a day or two, but I will get back to you). Please do note that email is not instantaneous communication; it is not a text message or a DM. I despite my best intentions, I recieve too many emails and try to manage a decent work-life balance. This means that you if you have questions for me and send them over email, you should be prepared for a response to take a day or two. In other words, do not send me an email right before an assignment is due or some other deadline.

### Student hours

Many faculty call these office hours. I prefer to use the term student hours since it is what they really are. Student hours are designated times I (and all faculty and TA’s) set aside each week for students to visit me in my office. I will always be in my office during these designated times, so feel free to stop by. These hours are your chance to ask questions about the course material, about university in general, or just to chat so that we can get to know one another. Many students come to student hours after a test wondering what they need to know to prepare for an exam; however, I encourage you to come with questions before the exam. Student hours are most helpful to students if you have done some studying before coming to my office and having concrete questions about material you are struggling with. When you come in with substantive questions about the course material, I can explain a course concept a different way or help you work through a problem.

## Recitation policies
